// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (m *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(m, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

type BaseResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BaseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type BasepageRequest struct {
	Base                 *BaseRequest `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Page                 int32        `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32        `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BasepageRequest) Reset()         { *m = BasepageRequest{} }
func (m *BasepageRequest) String() string { return proto.CompactTextString(m) }
func (*BasepageRequest) ProtoMessage()    {}
func (*BasepageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *BasepageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasepageRequest.Unmarshal(m, b)
}
func (m *BasepageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasepageRequest.Marshal(b, m, deterministic)
}
func (m *BasepageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasepageRequest.Merge(m, src)
}
func (m *BasepageRequest) XXX_Size() int {
	return xxx_messageInfo_BasepageRequest.Size(m)
}
func (m *BasepageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BasepageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BasepageRequest proto.InternalMessageInfo

func (m *BasepageRequest) GetBase() *BaseRequest {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *BasepageRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *BasepageRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type BasePageResponse struct {
	Base                 *BaseResponse `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Total                int32         `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BasePageResponse) Reset()         { *m = BasePageResponse{} }
func (m *BasePageResponse) String() string { return proto.CompactTextString(m) }
func (*BasePageResponse) ProtoMessage()    {}
func (*BasePageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}

func (m *BasePageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasePageResponse.Unmarshal(m, b)
}
func (m *BasePageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasePageResponse.Marshal(b, m, deterministic)
}
func (m *BasePageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasePageResponse.Merge(m, src)
}
func (m *BasePageResponse) XXX_Size() int {
	return xxx_messageInfo_BasePageResponse.Size(m)
}
func (m *BasePageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasePageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasePageResponse proto.InternalMessageInfo

func (m *BasePageResponse) GetBase() *BaseResponse {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *BasePageResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "user.BaseRequest")
	proto.RegisterType((*BaseResponse)(nil), "user.BaseResponse")
	proto.RegisterType((*BasepageRequest)(nil), "user.BasepageRequest")
	proto.RegisterType((*BasePageResponse)(nil), "user.BasePageResponse")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x8a, 0x83, 0x30,
	0x18, 0x84, 0x71, 0x4d, 0x64, 0xf7, 0x77, 0x97, 0x75, 0x83, 0x07, 0x8f, 0x12, 0xd8, 0xc5, 0x93,
	0x07, 0xb7, 0x4f, 0xd0, 0x5e, 0x5b, 0x90, 0xd0, 0x17, 0x88, 0xf4, 0x47, 0x84, 0xb6, 0xb1, 0x26,
	0xbe, 0x7f, 0xc9, 0x1f, 0x05, 0x7b, 0x9b, 0x49, 0x66, 0xe6, 0x0b, 0x01, 0xe8, 0xb4, 0xc5, 0x7a,
	0x9c, 0x8c, 0x33, 0x82, 0xcd, 0x16, 0x27, 0xf9, 0x05, 0xe9, 0x5e, 0x5b, 0x54, 0xf8, 0x98, 0xd1,
	0x3a, 0xb9, 0x83, 0xcf, 0x60, 0xed, 0x68, 0xee, 0x16, 0x85, 0x00, 0x76, 0x30, 0x17, 0x2c, 0xa2,
	0x32, 0xaa, 0xb8, 0x22, 0x2d, 0x32, 0x88, 0x4f, 0xb6, 0x2f, 0xde, 0xca, 0xa8, 0xfa, 0x50, 0x5e,
	0xca, 0x0e, 0xbe, 0x7d, 0x6b, 0xd4, 0xfd, 0x3a, 0x24, 0x7e, 0x81, 0x79, 0x16, 0x15, 0xd3, 0xe6,
	0xa7, 0xf6, 0xb0, 0x7a, 0x43, 0x52, 0x74, 0xed, 0xf7, 0x5b, 0xdd, 0x23, 0x8d, 0x71, 0x45, 0x5a,
	0xe4, 0xc0, 0x8f, 0xc3, 0x6d, 0x70, 0x45, 0x4c, 0x87, 0xc1, 0xc8, 0x16, 0x32, 0x5f, 0x6f, 0x89,
	0xb1, 0xbc, 0xee, 0xef, 0x05, 0x22, 0xb6, 0x90, 0x90, 0x58, 0x28, 0x39, 0xf0, 0xb3, 0x71, 0xfa,
	0xba, 0x60, 0x82, 0x69, 0x12, 0x60, 0x3e, 0xdb, 0x00, 0xbc, 0xaf, 0xcb, 0x5d, 0x42, 0x7f, 0xf3,
	0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x91, 0x15, 0x96, 0x5c, 0x29, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BaseClient is the client API for Base service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BaseClient interface {
}

type baseClient struct {
	cc *grpc.ClientConn
}

func NewBaseClient(cc *grpc.ClientConn) BaseClient {
	return &baseClient{cc}
}

// BaseServer is the server API for Base service.
type BaseServer interface {
}

// UnimplementedBaseServer can be embedded to have forward compatible implementations.
type UnimplementedBaseServer struct {
}

func RegisterBaseServer(s *grpc.Server, srv BaseServer) {
	s.RegisterService(&_Base_serviceDesc, srv)
}

var _Base_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.Base",
	HandlerType: (*BaseServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "base.proto",
}

// BasePageClient is the client API for BasePage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BasePageClient interface {
}

type basePageClient struct {
	cc *grpc.ClientConn
}

func NewBasePageClient(cc *grpc.ClientConn) BasePageClient {
	return &basePageClient{cc}
}

// BasePageServer is the server API for BasePage service.
type BasePageServer interface {
}

// UnimplementedBasePageServer can be embedded to have forward compatible implementations.
type UnimplementedBasePageServer struct {
}

func RegisterBasePageServer(s *grpc.Server, srv BasePageServer) {
	s.RegisterService(&_BasePage_serviceDesc, srv)
}

var _BasePage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.BasePage",
	HandlerType: (*BasePageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "base.proto",
}
